[project]
name = "adventofcode"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.6.1",
    "numpy>=2.3.4",
    "pulp>=3.3.0",
    "scipy>=1.16.3",
    "sympy>=1.14.0",
    "z3-solver>=4.15.4.0",
]
